set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

Plugin 'airblade/vim-gitgutter'
Plugin 'ap/vim-buftabline'
Plugin 'fatih/vim-go'
Plugin 'kien/ctrlp.vim'
Plugin 'NLKNguyen/papercolor-theme'
Plugin 'scrooloose/nerdtree'
Plugin 'SirVer/ultisnips'
Plugin 'Valloric/ListToggle'
Plugin 'Valloric/YouCompleteMe'
Plugin 'vim-syntastic/syntastic'

call vundle#end()            " required for Vundle
filetype plugin indent on    " required for Vundle

set autoread
set completeopt=noinsert,menuone
set expandtab
set hidden
set noerrorbells
set number
set shiftwidth=2
set tabstop=2
set wildmenu
set wildmode=longest,list,full

syntax on
syntax sync fromstart

nnoremap . :bn<CR>
nnoremap , :bp<CR>
nnoremap <M-/> :NERDTreeToggle<CR>
nnoremap <C-A-S-l> :LToggle<CR>
nnoremap <C-A-S-m> :bd<CR>
nnoremap <C-A-S-j> :lnext<CR>
nnoremap <C-A-S-k> :lprev<CR>
nnoremap gd :YcmCompleter GoTo<CR>

let g:buftabline_indicators = 1
let g:ctrlp_regexp = 1
let g:go_def_mode = 'godef'
let g:syntastic_auto_loc_list = 1
let g:syntastic_go_checkers = ['gotype']
let g:syntastic_markdown_checkers = []
let g:syntastic_python_checkers = ['pylint']
let g:syntastic_python_pylint_args = '-d R,C' " only display warnings and errors
let g:UltiSnipsExpandTrigger = "<M-.>"

augroup md_write
  autocmd!
  autocmd BufWritePost *.md :silent !async notes_written
augroup END

" source local vim scripts below
if filereadable(expand('~/.local.vim'))
  source ~/.local.vim
endif
