set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

Plugin 'airblade/vim-gitgutter'
Plugin 'ethantkoenig/vim-buftabline'
Plugin 'fatih/vim-go'
Plugin 'kien/ctrlp.vim'
Plugin 'NLKNguyen/papercolor-theme'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'rking/ag.vim'
Plugin 'rust-lang/rust.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'SirVer/ultisnips'
Plugin 'tpope/vim-abolish'
Plugin 'tpope/vim-commentary'
Plugin 'Valloric/ListToggle'
Plugin 'Valloric/YouCompleteMe'
Plugin 'w0rp/ale'

call vundle#end()            " required for Vundle
filetype plugin indent on    " required for Vundle

set autoread
set completeopt=noinsert,menuone
set expandtab
set hidden
set noerrorbells
set number
set shiftwidth=2
set tabstop=2
set wildmenu
set wildmode=longest,list,full

syntax on
syntax sync fromstart

inoremap <C-A-S-v> +
nnoremap . :BufTabLineNext<CR>
nnoremap , :BufTabLinePrev<CR>
nnoremap <A-.> :BufTabLineRight<CR>
nnoremap <A-,> :BufTabLineLeft<CR>
nnoremap <C-A-S-m> :BufTabLineClose<CR>
nnoremap <M-/> :NERDTreeToggle<CR>
nnoremap <C-A-S-l> :LToggle<CR>
nnoremap <C-A-S-j> :lnext<CR>
nnoremap <C-A-S-k> :lprev<CR>
nnoremap <C-A-S-v> "+p
vnoremap <C-A-S-v> "+p
nnoremap gd :YcmCompleter GoTo<CR>

let g:ale_linters = {'go': ['go build']}
let g:buftabline_indicators = 1
let g:buftabline_separators = 1
let g:ctrlp_regexp = 1
let g:go_def_mode = 'godef'
let g:go_fmt_command = "goimports"
let g:UltiSnipsExpandTrigger = "<M-.>"

augroup md_write
  autocmd!
  autocmd BufWritePost *.md :silent !async notes_written
augroup END

" source local vim scripts below
if filereadable(expand('~/.local.vim'))
  source ~/.local.vim
endif
